# Describes the format for available Tuya services

pull_devices:
  name: Pull devices
  description: Pull device list from Tuya server.

force_update:
  name: Force update
  description: Force all Tuya devices to pull data.
